"""empty message

Revision ID: 13e2c275d11a
Revises: 4324db001624
Create Date: 2019-11-06 11:12:01.213059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e2c275d11a'
down_revision = '4324db001624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dns_requests', sa.Column('raw_request', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dns_requests', 'raw_request')
    # ### end Alembic commands ###
