"""empty message

Revision ID: 3fef402b2909
Revises: d591b97ad11a
Create Date: 2019-05-20 07:23:45.820310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fef402b2909'
down_revision = 'd591b97ad11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_records',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.String(length=1024), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_dns_records_record'), 'dns_records', ['record'], unique=False)
    op.create_index(op.f('ix_dns_records_zone_id'), 'dns_records', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dns_records_zone_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_record'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_table('dns_records')
    # ### end Alembic commands ###
