"""empty message

Revision ID: 4324db001624
Revises: 
Create Date: 2019-06-23 18:04:14.886932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4324db001624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_listed_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_listed_tokens_id'), 'black_listed_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_black_listed_tokens_token'), 'black_listed_tokens', ['token'], unique=False)
    op.create_table('dns_responses',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_address', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_responses_id'), 'dns_responses', ['id'], unique=False)
    op.create_index(op.f('ix_dns_responses_name'), 'dns_responses', ['name'], unique=False)
    op.create_index(op.f('ix_dns_responses_protocol'), 'dns_responses', ['protocol'], unique=False)
    op.create_index(op.f('ix_dns_responses_source_address'), 'dns_responses', ['source_address'], unique=False)
    op.create_index(op.f('ix_dns_responses_type'), 'dns_responses', ['type'], unique=False)
    op.create_table('dns_servers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_servers_id'), 'dns_servers', ['id'], unique=False)
    op.create_index(op.f('ix_dns_servers_name'), 'dns_servers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('dns_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dns_server_id'], ['dns_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token'), 'api_tokens', ['token'], unique=False)
    op.create_table('zones',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dns_server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dns_server_id'], ['dns_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_domain'), 'zones', ['domain'], unique=True)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_ip'), 'zones', ['ip'], unique=False)
    op.create_table('dns_records',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.String(length=1024), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_dns_records_record'), 'dns_records', ['record'], unique=False)
    op.create_index(op.f('ix_dns_records_zone_id'), 'dns_records', ['zone_id'], unique=False)
    op.create_table('dns_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_address', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('dns_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dns_server_id'], ['dns_servers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_requests_id'), 'dns_requests', ['id'], unique=False)
    op.create_index(op.f('ix_dns_requests_name'), 'dns_requests', ['name'], unique=False)
    op.create_index(op.f('ix_dns_requests_protocol'), 'dns_requests', ['protocol'], unique=False)
    op.create_index(op.f('ix_dns_requests_source_address'), 'dns_requests', ['source_address'], unique=False)
    op.create_index(op.f('ix_dns_requests_type'), 'dns_requests', ['type'], unique=False)
    op.create_index(op.f('ix_dns_requests_zone_id'), 'dns_requests', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dns_requests_zone_id'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_type'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_source_address'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_protocol'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_name'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_id'), table_name='dns_requests')
    op.drop_table('dns_requests')
    op.drop_index(op.f('ix_dns_records_zone_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_record'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_zones_ip'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_domain'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_api_tokens_token'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dns_servers_name'), table_name='dns_servers')
    op.drop_index(op.f('ix_dns_servers_id'), table_name='dns_servers')
    op.drop_table('dns_servers')
    op.drop_index(op.f('ix_dns_responses_type'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_source_address'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_protocol'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_name'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_id'), table_name='dns_responses')
    op.drop_table('dns_responses')
    op.drop_index(op.f('ix_black_listed_tokens_token'), table_name='black_listed_tokens')
    op.drop_index(op.f('ix_black_listed_tokens_id'), table_name='black_listed_tokens')
    op.drop_table('black_listed_tokens')
    # ### end Alembic commands ###
