"""empty message

Revision ID: 53ecf6dfa8e4
Revises: b5e2ae1a9df2
Create Date: 2019-04-01 00:09:45.041875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ecf6dfa8e4'
down_revision = 'b5e2ae1a9df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'is_active')
    # ### end Alembic commands ###
