"""empty message

Revision ID: 88f825143aa2
Revises: a43f03aec33d
Create Date: 2019-03-25 01:16:28.883511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f825143aa2'
down_revision = 'a43f03aec33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###
