"""empty message

Revision ID: 97ebf31bd1e8
Revises: 352f6dead6a1
Create Date: 2019-03-25 02:08:25.979556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ebf31bd1e8'
down_revision = '352f6dead6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
