"""empty message

Revision ID: a43f03aec33d
Revises: 
Create Date: 2019-03-24 19:10:21.970250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43f03aec33d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_address', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_requests_id'), 'dns_requests', ['id'], unique=False)
    op.create_index(op.f('ix_dns_requests_name'), 'dns_requests', ['name'], unique=False)
    op.create_index(op.f('ix_dns_requests_protocol'), 'dns_requests', ['protocol'], unique=False)
    op.create_index(op.f('ix_dns_requests_source_address'), 'dns_requests', ['source_address'], unique=False)
    op.create_index(op.f('ix_dns_requests_type'), 'dns_requests', ['type'], unique=False)
    op.create_index(op.f('ix_dns_requests_zone_id'), 'dns_requests', ['zone_id'], unique=False)
    op.create_table('dns_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_address', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_responses_id'), 'dns_responses', ['id'], unique=False)
    op.create_index(op.f('ix_dns_responses_name'), 'dns_responses', ['name'], unique=False)
    op.create_index(op.f('ix_dns_responses_protocol'), 'dns_responses', ['protocol'], unique=False)
    op.create_index(op.f('ix_dns_responses_source_address'), 'dns_responses', ['source_address'], unique=False)
    op.create_index(op.f('ix_dns_responses_type'), 'dns_responses', ['type'], unique=False)
    op.create_index(op.f('ix_dns_responses_zone_id'), 'dns_responses', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_domain'), 'zones', ['domain'], unique=True)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_ip'), 'zones', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_ip'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_domain'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dns_responses_zone_id'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_type'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_source_address'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_protocol'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_name'), table_name='dns_responses')
    op.drop_index(op.f('ix_dns_responses_id'), table_name='dns_responses')
    op.drop_table('dns_responses')
    op.drop_index(op.f('ix_dns_requests_zone_id'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_type'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_source_address'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_protocol'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_name'), table_name='dns_requests')
    op.drop_index(op.f('ix_dns_requests_id'), table_name='dns_requests')
    op.drop_table('dns_requests')
    # ### end Alembic commands ###
