"""empty message

Revision ID: a6dc6a89a33b
Revises: 53ecf6dfa8e4
Create Date: 2019-04-01 16:41:40.241038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dc6a89a33b'
down_revision = '53ecf6dfa8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_listed_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_listed_tokens_id'), 'black_listed_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_black_listed_tokens_token'), 'black_listed_tokens', ['token'], unique=False)
    op.add_column('api_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dns_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_dns_requests_zone_id'), 'dns_requests', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'dns_requests', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.add_column('dns_responses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('zones', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'created_at')
    op.drop_column('users', 'created_at')
    op.drop_column('dns_responses', 'created_at')
    op.drop_constraint(None, 'dns_requests', type_='foreignkey')
    op.drop_index(op.f('ix_dns_requests_zone_id'), table_name='dns_requests')
    op.drop_column('dns_requests', 'created_at')
    op.drop_column('api_tokens', 'created_at')
    op.drop_index(op.f('ix_black_listed_tokens_token'), table_name='black_listed_tokens')
    op.drop_index(op.f('ix_black_listed_tokens_id'), table_name='black_listed_tokens')
    op.drop_table('black_listed_tokens')
    # ### end Alembic commands ###
