"""empty message

Revision ID: b5e2ae1a9df2
Revises: c1caf6fe909d
Create Date: 2019-03-31 05:05:21.012963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e2ae1a9df2'
down_revision = 'c1caf6fe909d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'expires_at')
    # ### end Alembic commands ###
