"""empty message

Revision ID: b6a4b9ca844b
Revises: a6dc6a89a33b
Create Date: 2019-04-01 17:01:38.600100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a4b9ca844b'
down_revision = 'a6dc6a89a33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('dns_server_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'dns_server_name')
    # ### end Alembic commands ###
