"""empty message

Revision ID: d8b944733252
Revises: 97ebf31bd1e8
Create Date: 2019-03-29 13:25:27.565677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b944733252'
down_revision = '97ebf31bd1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dns_requests_zone_id', table_name='dns_requests')
    op.drop_index('ix_dns_responses_zone_id', table_name='dns_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dns_responses_zone_id', 'dns_responses', ['zone_id'], unique=False)
    op.create_index('ix_dns_requests_zone_id', 'dns_requests', ['zone_id'], unique=False)
    # ### end Alembic commands ###
