"""empty message

Revision ID: ecbf1df79782
Revises: b6a4b9ca844b
Create Date: 2019-04-01 17:52:13.280105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbf1df79782'
down_revision = 'b6a4b9ca844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('dns_server_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'dns_server_name')
    # ### end Alembic commands ###
