"""empty message

Revision ID: cc0e5d3c0bb3
Revises: dffdb7f0813d
Create Date: 2019-11-10 19:42:03.227496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0e5d3c0bb3'
down_revision = 'dffdb7f0813d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_http_requests_path', table_name='http_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_http_requests_path', 'http_requests', ['path'], unique=False)
    # ### end Alembic commands ###
